# Generated by Django 4.2.8 on 2024-01-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reserva", "0002_petshop_reserva_petshop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petshop",
            name="numero",
            field=models.CharField(max_length=10, verbose_name="Número"),
        ),
    ]
