# Generated by Django 4.2.8 on 2024-02-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reserva", "0003_alter_petshop_numero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petshop",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={
                "ordering": ["data"],
                "verbose_name": "Reserva de Banho",
                "verbose_name_plural": "Reservas de Banho",
            },
        ),
    ]
